Готово
htmlacademy-javascript/2550293-kekstagram-2 pull request #10
Opened 2024-08-14 14:06 UTC by Kemyar2

2024-08-14 15:30 UTC, wonderjs requested changes

2024-08-14 15:30 UTC, wonderjs commented on js/submit-form.js
> +Пропишите тегу <form> 33 СТРОКА правильные значения атрибутов method и enctype и адрес action для отправки формы на сервер.
Значение нужно прописать тегу <form> в разметке (index.html) а не с помощью js

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +const pristinHeshtags = new Pristine(imgUploadForm, {
В качестве первого параметра мы передаем элемент формы. Не нужно создавать отдельный prisitine для каждого поля, требующего валидации, они находятся внутри одной формы

`pristinTextDescription` ниже - удалить, эту переменную переименовать в просто `pristine`

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +function validHashtagMaxLength(value) {
Почему function? По дефолту всегда использует стрелочные функции, исключение - функции, которым требуется всплытие или контекст. Переделать тут, ниже и в других модулях

Название функции должно содержать глагол - validateHashtag... Исправить здесь и везде ниже

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +  return value.split(' ').filter(Boolean).every((hashtag) => hashtag.length <= 20);
У тебя дублируется `value.split(' ').filter(Boolean)` во всех функциях, вынеси в отдельную - `getHashtags` / `getHashtagsFromString`

20 - в константу

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +const inputHeshtags = document.querySelector('.text__hashtags');
опечатка - H**a**shtags

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +  if (!validHashtagMaxLength(value) || !validUniqueHashtags(value)) {
В рамках функции оставь только конкретную проверку на символы после #

Чтобы остановить валидацию, когда какая-то из проверок уже ее прошла нужно добавить флаг true в addValidator. Также можно указать порядок проверок
![Снимок экрана 2024-08-14 в 17 21 42](https://github.com/user-attachments/assets/aee49805-77cd-4311-8348-7dd432f9ae13)

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +    if (!hashtag.startsWith('#')) {
Убираем лишние проверки

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +  return hashtags.length <= 5;
5 - в константу

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +    const hashtagPart = hashtag.slice(1).trim();
зачем тут trim?

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +pristinHeshtags.addValidator(inputHeshtags, validUniqueHashtags, 'Хештеги не могут повторяться');
Продумай порядок выполнения проверок, сообщения об ошибках я немного обновила
```
'Хештег должен начинаться с символа "#" (решетка)'
'Хештег не может состоять только из символа "#" (решётка)'
`Максимальное количество хештегов не должно превышать ${Hashtag.MAX_AMOUNT}`
'Строка после решётки должна состоять только из букв и чисел'
`Максимальное количество символов не должно превышать ${Hashtag.MAX_LENGTH}`
`Максимальное количество символов не должно превышать ${DESCRIPTION_MAX_LENGTH}`
```

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +const pristinTextDescription = new Pristine(textDescription, {
Убираем

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +  return value.length <= 140;
140 - константа, в сообщении об ошибке также используй значение из константы

2024-08-14 15:30 UTC, wonderjs commented on js/validation.js
> +  const isValidTextDescription = pristinTextDescription.validate();
Убираем всё лишнее
```
  if (!pristine.validate()) {
    evt.preventDefault();
  }
```

2024-08-14 15:30 UTC, wonderjs commented on js/submit-form.js
> +function openForm() {
Все функции не требующие всплытия меняем на стрелочные

2024-08-14 15:30 UTC, wonderjs commented on js/submit-form.js
> +  imgUploadForm.action = 'https://31.javascript.htmlacademy.pro/kekstagram';
Атрибуты формы прописываем в index.html

2024-08-14 15:30 UTC, wonderjs commented on js/submit-form.js
> +  textDescription.removeAttribute('required');
У этого элемента нет атрибута required, соответственно и удалять его не нужно

2024-08-14 15:30 UTC, wonderjs commented on js/submit-form.js
> +  addEventListeners();
Функции addEventListeners и removeEventListeners вынести до функций открытия / закрытия

2024-08-14 15:30 UTC, wonderjs commented on js/submit-form.js
> +function onButtonClick() {
лучше добавить что за кнопка onCloseButtonClick

2024-08-14 15:30 UTC, wonderjs commented on js/submit-form.js
> +  evt.preventDefault();
зачем preventDefault?

2024-08-14 15:43 UTC, wonderjs commented on js/submit-form.js
> +  if (isEscapeKey(evt)) {
Можно проще:
```
  if (isEscapeKey(evt) && inputHashtags !== document.activeElement && textDescription === document.activeElement) {
    closeForm();
  }
```

2024-08-15 13:19 UTC, wonderjs approved these changes

2024-08-15 13:19 UTC, wonderjs commented on js/submit-form.js
> +  imgUploadInput.value = '';
На закрытие формы нам нужно будет в итоге сбрасывать все введенные данные, так что здесь в следующем задании добавь сбор формы imgUploadForm.reset() и сбор ошибок валидации prisitine.reset()
Так как prisitine у тебя в другом модуле находится, ты можешь в нем сделать функцию `resetValidation`, внутри вызывать ресет пристина, потом эту функцию экспортировать и использовать в этом модуле.

2024-08-15 13:20 UTC, merged

2024-08-15 13:21 UTC, Kemyar2 commented on js/submit-form.js
> +  imgUploadInput.value = '';
Хорошо, сделаю