ТиПа_commit
htmlacademy-javascript/2550293-kekstagram-2 pull request #12
Opened 2024-08-21 13:43 UTC by Kemyar2

2024-08-21 15:24 UTC, wonderjs requested changes
Сильно намудрил, возможно потому что торопился. Пересмотри спокойно демку по учебному проекту, особенно разбери финальный результат что в какой модуле должно находиться и как они должны быть связаны.

2024-08-21 15:24 UTC, wonderjs commented on js/create-miniatures.js
> +const createMiniatures = (similarPhotos) => {
Загадочное переименование, а зачем? =) и почему similar?

2024-08-21 15:24 UTC, wonderjs commented on js/validation.js
> +pristine.addValidator(inputHashtags, validateHashtagsRequired, 'Поле хештегов не может быть пустым', 0, true);
??? У нас хештеги не обязательны для заполнения

2024-08-21 15:24 UTC, wonderjs commented on js/data.js
Удаляем модуль data и все функции из util, которые больше не используются

2024-08-21 15:24 UTC, wonderjs commented on js/server-api.js
> +const URL_FOR_RECEIPT = 'https://31.javascript.htmlacademy.pro/kekstagram/data';
Идем в демку и вдохновляемся https://up.htmlacademy.ru/javascript-individual/2/demos/13819#29

По сути ты можешь просто перенести весь модуль api.js из демки, поменяв основной урл

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +const errorImgUploadButton = () => {
Не поняла зачем это. Убираем, вдохновляемся демкой https://up.htmlacademy.ru/javascript-individual/2/demos/13819#30

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +    if (!isValid) {
Нам ничего дополнительно не нужно делать, если форма не валидна, у нас за это отвечает pristine

2024-08-21 15:24 UTC, wonderjs commented on js/main.js
> +const errorOnLoadTemplate = document.querySelector('#data-error').content.querySelector('.data-error');
Сделай отдельный модуль для сообщений об ошибках/успехе загрузки

2024-08-21 15:24 UTC, wonderjs commented on js/main.js
> +    }, 5000);
5000 - магия - в константу

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +const URL_FOR_SUBMIT_FORM = 'https://31.javascript.htmlacademy.pro/kekstagram';
Это должно быть в модуле api

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +  ERROR: 'Ошибка публикации. Попробуйте еще раз',
Перечисление
```
const SubmitButtonText = {
  IDLE: 'Опубликовать',
  SENDING: 'Публикую...'
};
```
Ошибку на кнопке показывать не нужно

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +const myHeaders = new Headers();
Это ты где нашел?

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +const getRequestConfig = (formData) => ({
Идем в демку по учебному проекту

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +const ResultTypes = {
вынеси всё что связано с мессаджами в отдельный модуль, экспортируй оттуда функцию showMessage

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +myHeaders.append('Content-Type', 'multipart/form-data');
не понимаю откуда ты это взял

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +  enableImgUploadButton();
Этого здесь быть не должно

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +const submitFormResult = (type) => {
showMessage

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +  const submitContainer = formTemplate.cloneNode(true);
`message`

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +  const closeWindow = () => {
`closeMessage`

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +  button.addEventListener('click', closeWindow);
```
button.addEventListener('click', () => {
  closeWindow();
})
```

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +      submitFormResult('success');
Сообщение об успешной отправке мы должно показать только после того как получили успешный ответ с бекенда

2024-08-21 15:24 UTC, wonderjs commented on js/submit-form.js
> +      fetch(
Идем пересматривать демо, здесь должен быть вызов функции отправки данных, которая должа быть создана и экспортирована в модуле api

2024-08-21 15:24 UTC, wonderjs commented on css/style.css
> -.form__item--invalid {
Не поняла чем тебе это класс не понравился и зачем ты его заменил

2024-08-22 04:14 UTC, Kemyar2 commented on js/create-miniatures.js
> +const createMiniatures = (similarPhotos) => {
Я посчитал, что слишком много уже слова Photos, поэтому начал потихоньку путаться. Решил так разграничить и отделить photo которые с сервера и photo которые нужны чисто для отрисовки

2024-08-22 04:15 UTC, Kemyar2 commented on js/create-miniatures.js
> +const createMiniatures = (similarPhotos) => {
Конечно, так лучше не делать, но в целом нормально

2024-08-22 04:16 UTC, Kemyar2 commented on js/data.js
Я просто закоментил, пусть лежат в файлах

2024-08-22 04:18 UTC, Kemyar2 commented on js/server-api.js
> +const URL_FOR_RECEIPT = 'https://31.javascript.htmlacademy.pro/kekstagram/data';
У вас кстати мужчина, который разбирает эту демку, у него только 26 пунктов, а в самой демке 31. Я еще это продублирую менеджеру

2024-08-22 04:19 UTC, Kemyar2 commented on js/server-api.js
> +const URL_FOR_RECEIPT = 'https://31.javascript.htmlacademy.pro/kekstagram/data';
Видимо добавили после

2024-08-22 04:21 UTC, Kemyar2 commented on js/submit-form.js
> +const errorImgUploadButton = () => {
Вы про что? Если про errorImgUploadButton, то я просто заменю enable версию

2024-08-22 04:26 UTC, Kemyar2 commented on js/submit-form.js
> +    if (!isValid) {
В таком случае submitFormResult('error') будет в ветке else, её же нужно куда-то перенести

2024-08-22 04:36 UTC, Kemyar2 commented on js/submit-form.js
> +const URL_FOR_SUBMIT_FORM = 'https://31.javascript.htmlacademy.pro/kekstagram';
Имеете ввиду const URL_FOR_SUBMIT_FORM = 'https://31.javascript.htmlacademy.pro/kekstagram'; а потом просто импортировать? Окей

2024-08-22 04:54 UTC, Kemyar2 commented on js/submit-form.js
> +const myHeaders = new Headers();
Часть с const myHeaders = new Headers()? Если говорить про метод реализации, то на MDN написано про раздел в заголовками. В тз указан тип multipart/form-data, я просто взял часть их кода и понял названия. Я подумал, что так будет более красивее, чем писать Content-Type внутри fetch. А потом вывел в функцию-объект все остальное

2024-08-22 04:55 UTC, Kemyar2 commented on js/submit-form.js
> +const myHeaders = new Headers();
Я подумал, что если MDN пишет так, то это на 100% верно и правильно, разве не так?

2024-08-22 05:02 UTC, Kemyar2 commented on js/submit-form.js
> +  const submitContainer = formTemplate.cloneNode(true);
Имеете ввиду что-то типа formTemplateMessage и тп?

2024-08-22 05:05 UTC, Kemyar2 commented on js/submit-form.js
> +  const submitContainer = formTemplate.cloneNode(true);
Поменял на messageContainer и messageTemplate

2024-08-22 05:26 UTC, Kemyar2 commented on css/style.css
> -.form__item--invalid {
Мне лично ничем, да вот только в тз сказано "Ошибки выводятся внутри блока .img-upload__field-wrapper соответствующего поля. Также, если поле заполнено неверно, блоку, в котором выводится текст ошибки, добавляется класс .img-upload__field-wrapper--error." Класс уже был готов, зачем добавлять свой класс, я его создал как затычку, если бы не говорили про .img-upload__field-wrapper--error, я бы ничего не трогал, но зачем плодить классы?

2024-08-22 06:02 UTC, Kemyar2 commented on js/submit-form.js
> +      fetch(
У нас кстати поломалась немного логика валидатора. Если я начну строку с любого символа, кроме #, то он мне напишет "Хештег не может состоять только из символа "#" (решётка)", а ожидалось "Хештег должен начинаться с символа "#" (решетка)". При этом, если я напишу два символа, первый из которых будет НЕ решетка, то я получу ошибку  "Хештег должен начинаться с символа "#" (решетка)", что абсолютно верно. Максимальное кол-во хештегов имеют на деле меньший приоритет, чем validateHashtagStartWith, и показывается только после отработки validateHashtagStartWith, что также не является нормой. Я попробую это исправить

2024-08-22 06:09 UTC, Kemyar2 commented on js/submit-form.js
> +      fetch(
UPD: Первую ошибку поправил, вторую не знаю как

2024-08-22 10:46 UTC, wonderjs requested changes
Удалить все неиспользуемые модули и функции
[Б12.](https://up.htmlacademy.ru/javascript-individual/2/criteries#b12) В коде проекта нет файлов, модулей и частей кода, которые не используются, **включая закомментированные участки кода**.

2024-08-22 10:46 UTC, wonderjs commented on js/alerts.js
> +  function onEscKeydownClick (event) {
Click здесь уже лишнее, это обработчик именно на Keydown

2024-08-22 10:46 UTC, wonderjs commented on js/alerts.js
> +  const errorOnLoadTemplate = document.querySelector('#data-error').content.querySelector('.data-error');
Можно назвать `uploadErrorTemplate`
Поиск темплейта выносим из функции наверх [Д21.](https://up.htmlacademy.ru/javascript-individual/2/criteries#d21) Поиск элементов по селекторам делается минимальное количество раз, после этого ссылки на элементы сохраняются.

2024-08-22 10:46 UTC, wonderjs commented on js/data.js
[Б12.](https://up.htmlacademy.ru/javascript-individual/2/criteries#b12) В коде проекта нет файлов, модулей и частей кода, которые не используются, **включая закомментированные участки кода**.

2024-08-22 10:46 UTC, wonderjs commented on js/alerts.js
> +  const messageTemplate = document.querySelector(templateId).content.querySelector(containerClass);
Минусы - при каждом вызове функции ты будешь искать темплейты, лучше вынести их в начало модуля 
```
const successTemplate = document.querySelector('#success').content.querySelector('.success');
const errorTemplate = document.querySelector('#error').content.querySelector('.error');
```
[Д21.](https://up.htmlacademy.ru/javascript-individual/2/criteries#d21) Поиск элементов по селекторам делается минимальное количество раз, после этого ссылки на элементы сохраняются.

2024-08-22 10:46 UTC, wonderjs commented on js/submit-form.js
> +      showSubmissionMessage('error');
Это здесь не нужно, если мы данные не отправили, то и ошибку нам показывать не нужно.

2024-08-22 12:25 UTC, wonderjs commented on js/alerts.js
> +const errorButton = errorTemplate.querySelector('.error__button');
А вот кнопки нужно было оставить внутри функции, иначе обработчики не будут работать. Мы клонируем темплейт и вешаем обработчики именно на копию и кнопки внутри нее

2024-08-22 12:33 UTC, merged