4.16. Больше деталей
htmlacademy-javascript/2550293-kekstagram-2 pull request #4
Opened 2024-07-08 15:20 UTC by Kemyar2

2024-07-08 19:23 UTC, wonderjs requested changes
Потерялся ключ description в объекте фото.

2024-07-08 19:23 UTC, wonderjs commented on js/main.js
> +const REVIEW = ['Всё отлично!', 'Когда вы делаете фотографию, хорошо бы убирать палец из кадра. В конце концов это просто непрофессионально.', 'Моя бабушка случайно чихнула с фотоаппаратом в руках и
[Б5.](https://up.htmlacademy.ru/javascript-individual/2/criteries#b5) Массивы названы существительными во множественном числе.

2024-07-08 19:23 UTC, wonderjs commented on js/main.js
> +const NAME = [
[Б5.](https://up.htmlacademy.ru/javascript-individual/2/criteries#b5) Массивы названы существительными во множественном числе.

2024-07-08 19:23 UTC, wonderjs commented on js/main.js
> +function getRandomNumberFrom1To25() {
Можно обойтись без таких загадочных функций =))) 
Разбери метод Array.from, особенно вот такой пример:
```
// Генерирования последовательности чисел
Array.from({ length: 5 }, (v, k) => k);
// [0, 1, 2, 3, 4]
```

2024-07-08 19:23 UTC, wonderjs commented on js/main.js
> +  const index = getRandomNumberFrom1To25();
лучше чтобы url должен соответствол id фото

2024-07-08 19:23 UTC, wonderjs commented on js/main.js
> +const createObjects = () => ([
Лучше называть функции так, чтобы было понятно что они делают `createPhoto`

2024-07-08 19:23 UTC, wonderjs commented on js/main.js
> +    likes: getRandomInteger(15, 200),
[Д19.](https://up.htmlacademy.ru/javascript-individual/2/criteries#d19) В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.
15, 200 - магия, в константу

2024-07-08 19:23 UTC, wonderjs commented on js/main.js
> +    comments: [{
Количество комментариев к каждой фотографии — случайное число от 0 до 30. 
Вынеси в отдельную функцию создание массива комментариев.

2024-07-08 19:23 UTC, wonderjs commented on js/main.js
> +const message = createRandomMessage();
Сейчас у тебя у всех комментариев будет одинаковый message. А мы хотим чтобы у всех был разный. Не нужно сохранять здесь результат вызова в переменную.

2024-07-08 19:23 UTC, wonderjs commented on js/main.js
> +for (let i = 0; i < 25; i++) {
25 - магия
Читаем про Array.from 
Делаем функцию которая создаст и вернет массив из 25 объектов. В конце модуля вызываем функцию.

2024-07-08 19:23 UTC, wonderjs commented on js/main.js
> +  console.log(JSON.stringify(createObjects(), null, 2));
Зачем тебе JSON.stringify?

2024-07-09 12:23 UTC, Kemyar2 commented on js/main.js
> +const message = createRandomMessage();
Нет, на самом деле будет всегда разный. Так как функция с замыканием и берет каждый раз разный индекс у массива, message будет разный. Конечно, в 25 объектах они в любом случае повторятся из-за того, что их всего 6. Также, если это функция с замыканием, то и вызываю я message() в итоге

2024-07-09 12:25 UTC, Kemyar2 commented on js/main.js
> +  console.log(JSON.stringify(createObjects(), null, 2));
JSON.stringify расширяет область чтения вложенных объектов. JS не в состоянии в массиве прочитать массив, который состоит из объектов. Он вернет     comments: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ], для него это просто объекты. JSON.stringify убирает такую проблему, хотя и является небольшим костылем

2024-07-09 14:09 UTC, wonderjs requested changes

2024-07-09 14:09 UTC, wonderjs commented on js/main.js
> +const MAX_NUMBERS_LIKES = 200;
[Б10.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b10) Список констант идёт перед основным кодом.
Можно для лайков использовать перечисления:
```
const Like = {
  MIN: 15,
  MAX: 200
};
```

2024-07-09 14:09 UTC, wonderjs commented on js/main.js
> +const NUMBER_PHOTOS = 25;
[Б10.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b10) Список констант идёт перед основным кодом.

2024-07-09 14:09 UTC, wonderjs commented on js/main.js
> +      name: NAMES[getRandomInteger(0, NAMES.length - 1)]
Можно сделать функцию для получения рандомного элемента массива:
```
const getRandomElement = (elements) => elements[getRandomNumber(0, elements.length - 1)];
```
И использовать тут и для description

2024-07-09 14:09 UTC, wonderjs commented on js/main.js
> +      avatar: `img/avatar-${getRandomInteger(1, 6)}.svg`,
1, 6 - лучше в константы / перечисление
```
const Avatar = {
  MIN: 1,
  MAX: 6
};
```

2024-07-09 14:09 UTC, wonderjs commented on js/main.js
> +const createRandomIdGenerator = () => {
Избыточная функция, у тебя уже есть Array.from для генерации фото
```
Array.from({ length: NUMBER_PHOTOS }, createPhoto)
```
Используй индекс элементов:
```
Array.from({length: NUMBER_PHOTOS}, (item, index) => createPhoto(index + 1));
```
Те у тебя в качестве параметра функции createPhoto уже будет по сути id

2024-07-09 14:09 UTC, wonderjs commented on js/main.js
> +const photos = Array.from({ length: NUMBER_PHOTOS }, createPhoto);
Лучше сделать функцию:
```
const createPhotos = () => Array.from(...);
```

2024-07-09 14:09 UTC, wonderjs commented on js/main.js
> +  const numComments = getRandomInteger(0, 30);
Магия
```
const Comment = {
  MIN: 0,
  MAX: 30
};
```

2024-07-09 14:09 UTC, wonderjs commented on js/main.js
> +  for (let i = 0; i < numComments; i++) {
Можно опять использовать Array.from, вынеся функцию создания одного комментария
```
Array.from({length: numComments}, createComment)
```

2024-07-11 15:56 UTC, merged